name: Linting Generated Blueprints

on:
  push:
  workflow_dispatch: {}

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Install Dependencies
        run: |
          go mod download

  framework_matrix:
    needs: install_dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        framework:
          [chi, gin, fiber, gorilla/mux, httprouter, standard-library, echo]
        goVersion: ["1.20"]
    steps:
      - uses: actions/checkout@v4
      # - name: Setup Go
        # uses: actions/setup-go@v4
        # with:
        #   go-version: ${{ matrix.goVersion }}
      - name: build templates
        run: |
          script -c "go run main.go create -n ${{ matrix.framework }} -f ${{ matrix.framework}}" /dev/null
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          working-directory: ${{ matrix.framework }}
          args: --timeout=5m
